# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PONDcontrol(object):
    def setupUi(self, PONDcontrol):
        PONDcontrol.setObjectName("PONDcontrol")
        PONDcontrol.resize(628, 414)
        font = QtGui.QFont()
        font.setPointSize(24)
        PONDcontrol.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PONDcontrol)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(PONDcontrol)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.line_3 = QtWidgets.QFrame(PONDcontrol)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.onTime = QtWidgets.QTimeEdit(PONDcontrol)
        self.onTime.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.onTime.setFont(font)
        self.onTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.onTime.setObjectName("onTime")
        self.verticalLayout_5.addWidget(self.onTime)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.onDown = QtWidgets.QPushButton(PONDcontrol)
        self.onDown.setMinimumSize(QtCore.QSize(0, 50))
        self.onDown.setObjectName("onDown")
        self.horizontalLayout_4.addWidget(self.onDown)
        self.onUp = QtWidgets.QPushButton(PONDcontrol)
        self.onUp.setMinimumSize(QtCore.QSize(0, 50))
        self.onUp.setObjectName("onUp")
        self.horizontalLayout_4.addWidget(self.onUp)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(PONDcontrol)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.line_4 = QtWidgets.QFrame(PONDcontrol)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.offTime = QtWidgets.QTimeEdit(PONDcontrol)
        self.offTime.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.offTime.setFont(font)
        self.offTime.setWrapping(False)
        self.offTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.offTime.setMaximumTime(QtCore.QTime(23, 59, 50))
        self.offTime.setObjectName("offTime")
        self.verticalLayout_4.addWidget(self.offTime)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.offDown = QtWidgets.QPushButton(PONDcontrol)
        self.offDown.setMinimumSize(QtCore.QSize(0, 50))
        self.offDown.setObjectName("offDown")
        self.horizontalLayout_5.addWidget(self.offDown)
        self.offUp = QtWidgets.QPushButton(PONDcontrol)
        self.offUp.setMinimumSize(QtCore.QSize(0, 50))
        self.offUp.setObjectName("offUp")
        self.horizontalLayout_5.addWidget(self.offUp)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.setTimes = QtWidgets.QPushButton(PONDcontrol)
        self.setTimes.setMinimumSize(QtCore.QSize(0, 50))
        self.setTimes.setObjectName("setTimes")
        self.verticalLayout_3.addWidget(self.setTimes)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(PONDcontrol)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.line = QtWidgets.QFrame(PONDcontrol)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.ledMode = QtWidgets.QComboBox(PONDcontrol)
        self.ledMode.setMinimumSize(QtCore.QSize(300, 50))
        self.ledMode.setObjectName("ledMode")
        self.verticalLayout_6.addWidget(self.ledMode)
        spacerItem1 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(PONDcontrol)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.line_2 = QtWidgets.QFrame(PONDcontrol)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.override = QtWidgets.QPushButton(PONDcontrol)
        self.override.setMinimumSize(QtCore.QSize(300, 50))
        self.override.setObjectName("override")
        self.verticalLayout.addWidget(self.override)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sysOff = QtWidgets.QPushButton(PONDcontrol)
        self.sysOff.setEnabled(False)
        self.sysOff.setMinimumSize(QtCore.QSize(150, 50))
        self.sysOff.setObjectName("sysOff")
        self.horizontalLayout.addWidget(self.sysOff)
        self.sysOn = QtWidgets.QPushButton(PONDcontrol)
        self.sysOn.setEnabled(False)
        self.sysOn.setMinimumSize(QtCore.QSize(150, 50))
        self.sysOn.setObjectName("sysOn")
        self.horizontalLayout.addWidget(self.sysOn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.automatic = QtWidgets.QPushButton(PONDcontrol)
        self.automatic.setEnabled(False)
        self.automatic.setMinimumSize(QtCore.QSize(300, 50))
        self.automatic.setObjectName("automatic")
        self.verticalLayout.addWidget(self.automatic)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PONDcontrol)
        self.offDown.clicked.connect(self.offTime.stepDown)
        self.offUp.clicked.connect(self.offTime.stepUp)
        self.onUp.clicked.connect(self.onTime.stepUp)
        self.onDown.clicked.connect(self.onTime.stepDown)
        QtCore.QMetaObject.connectSlotsByName(PONDcontrol)

    def retranslateUi(self, PONDcontrol):
        _translate = QtCore.QCoreApplication.translate
        PONDcontrol.setWindowTitle(_translate("PONDcontrol", "POND Controller"))
        self.label.setText(_translate("PONDcontrol", "On Time"))
        self.onTime.setDisplayFormat(_translate("PONDcontrol", "HH:mm"))
        self.onDown.setText(_translate("PONDcontrol", "Down"))
        self.onUp.setText(_translate("PONDcontrol", "Up"))
        self.label_2.setText(_translate("PONDcontrol", "Off Time"))
        self.offTime.setDisplayFormat(_translate("PONDcontrol", "HH:mm"))
        self.offDown.setText(_translate("PONDcontrol", "Down"))
        self.offUp.setText(_translate("PONDcontrol", "Up"))
        self.setTimes.setText(_translate("PONDcontrol", "Set Times"))
        self.label_3.setText(_translate("PONDcontrol", "LED Mode"))
        self.label_4.setText(_translate("PONDcontrol", "Master Control"))
        self.override.setText(_translate("PONDcontrol", "Override"))
        self.sysOff.setText(_translate("PONDcontrol", "System Off"))
        self.sysOn.setText(_translate("PONDcontrol", "System On"))
        self.automatic.setText(_translate("PONDcontrol", "Automatic"))

