# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pin.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Pin(object):
    def setupUi(self, Pin):
        Pin.setObjectName("Pin")
        Pin.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(24)
        Pin.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Pin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.number = QtWidgets.QLineEdit(Pin)
        self.number.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.number.setFont(font)
        self.number.setInputMask("")
        self.number.setText("")
        self.number.setEchoMode(QtWidgets.QLineEdit.Password)
        self.number.setAlignment(QtCore.Qt.AlignCenter)
        self.number.setReadOnly(True)
        self.number.setClearButtonEnabled(False)
        self.number.setObjectName("number")
        self.verticalLayout.addWidget(self.number)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.but1 = QtWidgets.QPushButton(Pin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but1.sizePolicy().hasHeightForWidth())
        self.but1.setSizePolicy(sizePolicy)
        self.but1.setObjectName("but1")
        self.horizontalLayout.addWidget(self.but1)
        self.but2 = QtWidgets.QPushButton(Pin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but2.sizePolicy().hasHeightForWidth())
        self.but2.setSizePolicy(sizePolicy)
        self.but2.setObjectName("but2")
        self.horizontalLayout.addWidget(self.but2)
        self.but3 = QtWidgets.QPushButton(Pin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but3.sizePolicy().hasHeightForWidth())
        self.but3.setSizePolicy(sizePolicy)
        self.but3.setObjectName("but3")
        self.horizontalLayout.addWidget(self.but3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.but4 = QtWidgets.QPushButton(Pin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but4.sizePolicy().hasHeightForWidth())
        self.but4.setSizePolicy(sizePolicy)
        self.but4.setObjectName("but4")
        self.horizontalLayout_3.addWidget(self.but4)
        self.but5 = QtWidgets.QPushButton(Pin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but5.sizePolicy().hasHeightForWidth())
        self.but5.setSizePolicy(sizePolicy)
        self.but5.setObjectName("but5")
        self.horizontalLayout_3.addWidget(self.but5)
        self.but6 = QtWidgets.QPushButton(Pin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but6.sizePolicy().hasHeightForWidth())
        self.but6.setSizePolicy(sizePolicy)
        self.but6.setObjectName("but6")
        self.horizontalLayout_3.addWidget(self.but6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.but7 = QtWidgets.QPushButton(Pin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but7.sizePolicy().hasHeightForWidth())
        self.but7.setSizePolicy(sizePolicy)
        self.but7.setObjectName("but7")
        self.horizontalLayout_2.addWidget(self.but7)
        self.but8 = QtWidgets.QPushButton(Pin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but8.sizePolicy().hasHeightForWidth())
        self.but8.setSizePolicy(sizePolicy)
        self.but8.setObjectName("but8")
        self.horizontalLayout_2.addWidget(self.but8)
        self.but9 = QtWidgets.QPushButton(Pin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but9.sizePolicy().hasHeightForWidth())
        self.but9.setSizePolicy(sizePolicy)
        self.but9.setObjectName("but9")
        self.horizontalLayout_2.addWidget(self.but9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.enter = QtWidgets.QPushButton(Pin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enter.sizePolicy().hasHeightForWidth())
        self.enter.setSizePolicy(sizePolicy)
        self.enter.setMinimumSize(QtCore.QSize(0, 50))
        self.enter.setObjectName("enter")
        self.verticalLayout.addWidget(self.enter)

        self.retranslateUi(Pin)
        QtCore.QMetaObject.connectSlotsByName(Pin)

    def retranslateUi(self, Pin):
        _translate = QtCore.QCoreApplication.translate
        Pin.setWindowTitle(_translate("Pin", "Form"))
        self.but1.setText(_translate("Pin", "1"))
        self.but2.setText(_translate("Pin", "2"))
        self.but3.setText(_translate("Pin", "3"))
        self.but4.setText(_translate("Pin", "4"))
        self.but5.setText(_translate("Pin", "5"))
        self.but6.setText(_translate("Pin", "6"))
        self.but7.setText(_translate("Pin", "7"))
        self.but8.setText(_translate("Pin", "8"))
        self.but9.setText(_translate("Pin", "9"))
        self.enter.setText(_translate("Pin", "ENTER"))

